In [ ]:
!pip install -q -U ydata-profiling[notebook]

# 2. Importamos lo necesario
import pandas as pd
from ydata_profiling import ProfileReport

# 3. Cargamos tus datos (ajusta el nombre de tu archivo aquí)
# df = pd.read_csv('tu_archivo.csv')

print("✅ Entorno listo: ydata-profiling instalado y pandas cargado.")

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('tips.csv')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_csv = pd.read_csv('/content/drive/MyDrive/Carga/tips.csv')
df_csv

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
url ='https://docs.google.com/spreadsheets/d/1FRLM9E7W4VVWEP_sx9QWq2w0okWfbGJ3IWFFXRL0-70/export?format=csv'
df1 =pd.read_csv(url)
df1

    total_bill    tip     sex smoker   day    time  size
0        50,81  10.00    Male    Yes   Sat  Dinner     3
1        48,33   9.00    Male     No   Sat  Dinner     4
2        48,27   6.73    Male     No   Sat  Dinner     4
3        48,17   5.00    Male     No   Sun  Dinner     6
4        45,35   3.50    Male    Yes   Sun  Dinner     3
..         ...    ...     ...    ...   ...     ...   ...
239       7,51   2.00    Male     No  Thur   Lunch     2
240       7,25   1.00  Female     No   Sat  Dinner     1
241       7,25   5.15    Male    Yes   Sun  Dinner     2
242       5,75   1.00  Female    Yes   Fri  Dinner     2
243       3,07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 7 columns]

In [ ]:
df.tail() #los ultimos indices,ver correlatividad

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
df.sample()

    total_bill   tip   sex smoker  day    time  size
20       17.92  4.08  Male     No  Sat  Dinner     2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [ ]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [ ]:
df.describe(include='object')

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [ ]:
df['sex'].describe(include='object')

count      244
unique       2
top       Male
freq       157
Name: sex, dtype: object

In [ ]:
df.duplicated().sum()

np.int64(1)

In [ ]:
df[df.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [ ]:
df[df.duplicated(keep=False)]

     total_bill  tip     sex smoker   day   time  size
198        13.0  2.0  Female    Yes  Thur  Lunch     2
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [ ]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
! pip install ydata-profiling

In [ ]:
from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="EDA Report", explorative=True)
profile.to_file("ydata_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 7/7 [00:00<00:00, 74.30it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('Orders.xlsx')
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,Nan
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
9,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
10,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
11,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
12,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
13,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
14,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
15,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
16,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer ID  17 non-null     int64
 1   Order ID     17 non-null     int64
 2   Product      17 non-null     object
 3   Stock        17 non-null     int64
 4   Date         17 non-null     datetime64[ns]
 5   Ventas       14 non-null     float64
 6   Cost         17 non-null     int64
 7   Categoria    17 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(4), object(2)
memory usage: 1.2+ KB

In [ ]:
df.describe(include='object')

                    Product Categoria
count                    17        17
unique                    9         4
top     Chocolate Con Leche       Nan
freq                      3         7

In [ ]:
df.describe()

,Customer ID,Order ID,Stock,Date,Ventas,Cost
count,17.000000,17.000000,17.000000,17,14.000000,17.000000
mean,3.705882,655550.529412,1131.352941,2020-03-10 19:45:52.941176576,5922.857143,2262.705882
min,1.000000,140794.000000,292.000000,2019-09-01 00:00:00,1460.000000,584.000000
25%,3.000000,505339.000000,549.000000,2019-09-01 00:00:00,2745.000000,1098.000000
50%,5.000000,703997.000000,883.000000,2020-06-01 00:00:00,3940.000000,1766.000000
75%,5.000000,738711.000000,1006.000000,2020-08-01 00:00:00,10527.500000,2012.000000
max,5.000000,898637.000000,2518.000000,2020-09-01 00:00:00,12590.000000,5036.000000
std,1.611083,214475.538027,798.441133,NaN,4379.902402,1596.882266

In [ ]:
df.describe(include='all')

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
count,17.000000,17.000000,17,17.000000,17,14.000000,17.000000,17
unique,NaN,NaN,9,NaN,NaN,NaN,NaN,4
top,NaN,NaN,Chocolate Con Leche,NaN,NaN,NaN,NaN,Nan
freq,NaN,NaN,3,NaN,NaN,NaN,NaN,7
mean,3.705882,655550.529412,NaN,1131.352941,2020-03-10 19:45:52.941176576,5922.857143,2262.705882,NaN
min,1.000000,140794.000000,NaN,292.000000,2019-09-01 00:00:00,1460.000000,584.000000,NaN
25%,3.000000,505339.000000,NaN,549.000000,2019-09-01 00:00:00,2745.000000,1098.000000,NaN
50%,5.000000,703997.000000,NaN,883.000000,2020-06-01 00:00:00,3940.000000,1766.000000,NaN
75%,5.000000,738711.000000,NaN,1006.000000,2020-08-01 00:00:00,10527.500000,2012.000000,NaN
max,5.000000,898637.000000,NaN,2518.000000,2020-09-01 00:00:00,12590.000000,5036.000000,NaN
std,1.611083,214475.538027,NaN,798.441133,NaN,4379.902402,1596.882266,NaN

In [ ]:
df["Product"].value_counts()

Product
Chocolate Con Leche       3
Chocolate Asavache        3
Chocolate Pinterex        3
Chocolate Caramelo        3
Chocolate Negro           1
Chocolate Semidulce       1
Chocolate Chip            1
Chocolate Blanco          1
Chocolate Negro Amargo    1
Name: count, dtype: int64

In [ ]:
# Veamos si hay registros duplicados y cuántos son
df.duplicated().sum()

np.int64(8)

In [ ]:
df[df.duplicated()]

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
9,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
10,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
11,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
12,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
13,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
14,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
15,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
16,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
df = pd.read_excel('Orders.xlsx')
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,Nan
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
9,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
10,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
11,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
12,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
13,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
14,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
15,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
16,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
df_duplicados = df[df.duplicated(keep=False)]
df_duplicados

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
9,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
10,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
11,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
12,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular
13,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
14,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
15,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
16,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
df = df.drop_duplicates()

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,Nan
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
!pip install -q -U ydata-profiling[notebook]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 86.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 56.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.8/59.8 kB 3.4 MB/s eta 0:00:00

In [ ]:
import pandas as pd
from ydata_profiling import ProfileReport

In [ ]:
# Importar un metodo automatizado
reporte = ProfileReport(df, title="Mi Análisis de Datos")
reporte.to_notebook_iframe()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 8/8 [00:00<00:00, 86.86it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df[df.isnull().any(axis=1)]

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar

In [ ]:
import numpy as np

# Reemplaza la palabra "NaN" por un nulo real de forma global
df = df.replace('NaN', np.nan)

In [ ]:
df.isnull().sum()

Customer ID    0
Order ID       0
Product        0
Stock          0
Date           0
Ventas         1
Cost           0
Categoria      0
dtype: int64

In [ ]:
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,Nan
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,Nan
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,Nan
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
print(type(df.loc[0, 'Categoria']))

<class 'str'>

In [ ]:
# 1. Limpia espacios en blanco (por si acaso) y reemplaza el texto "NaN"
df['Ventas'] = df['Ventas'].astype(str).str.strip().replace(['NaN', 'nan', 'None'], np.nan)

# 2. Convierte la columna a número real
df['Ventas'] = pd.to_numeric(df['Ventas'], errors='coerce')

# 3. Verifica ahora
print(f"Nulos encontrados en Ventas: {df['Ventas'].isnull().sum()}")

#¿Por qué este funciona?
#Porque primero convierte todo a texto limpio, quita espacios, reemplaza las variantes de la palabra "NaN" y finalmente fuerza a que la columna sea numérica.
#¿Qué número te sale ahora en el sum() de Ventas? ¡Debería aparecer el total real de tus pruebas!"""

Nulos encontrados en Ventas: 1

In [ ]:
print(df['Ventas'].unique())

[ 1460.  4870. 12590.  5030.  1835.    nan  2745.  3940. 12360.]

In [ ]:
1. #Primero aseguramos que todo lo que diga "nan" sea texto limpio
df['Categoria'] = df['Categoria'].astype(str).str.strip()

# 2. Reemplazamos la PALABRA "nan" por el número 0
df['Categoria'] = df['Categoria'].replace(['nan', 'Nan', 'None'], 0)

# 3. Por si acaso quedaba algún nulo real (np.nan), también lo llenamos con 0
df['Categoria'] = df['Categoria'].fillna(0)

In [ ]:
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,0
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar
5,5,889571,Chocolate Caramelo,883,2020-08-01,NaN,1766,Estandar
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,0
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,0
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular

In [ ]:
# le asigno un nuevo valor a la columna de ventas indice 5
df.at[5, 'Ventas'] = 6300

In [ ]:
print(df['Ventas'])

0     1460.0
1     4870.0
2    12590.0
3     5030.0
4     1835.0
5     6300.0
6     2745.0
7     3940.0
8    12360.0
Name: Ventas, dtype: float64

In [ ]:
# Creamos la columna 'Neto' restando Ventas y Cost
df = df.assign(Neto = df['Ventas'] - df['Cost'])

In [ ]:
# Calculamos el % de ganancia sobre el costo
df = df.assign(Porcentaje_Ganancia = (df['Neto'] / df['Cost']) * 100)

# Redondeamos a 2 decimales para que se vea limpio
df['Porcentaje_Ganancia'] = df['Porcentaje_Ganancia'].round(2)

In [ ]:
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria,Neto,Porcentaje_Ganancia
0,3,266868,Chocolate Negro,292,2020-02-01,1460.0,584,0,876.0,150.00
1,3,140794,Chocolate Negro Amargo,974,2020-02-01,4870.0,1948,Bueno,2922.0,150.00
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular,7554.0,150.00
3,4,640447,Chocolate Chip,1006,2020-06-01,5030.0,2012,Bueno,3018.0,150.00
4,2,898637,Chocolate Semidulce,367,2020-07-01,1835.0,734,Estandar,1101.0,150.00
5,5,889571,Chocolate Caramelo,883,2020-08-01,6300.0,1766,Estandar,4534.0,256.74
6,1,738711,Chocolate Asavache,549,2019-09-01,2745.0,1098,0,1647.0,150.00
7,5,505339,Chocolate Pinterex,788,2019-09-01,3940.0,1576,0,2364.0,150.00
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular,7416.0,150.00

In [ ]:
# le asigno un nuevo valor a la columna Categoria a los indices elegidos
df.at[6, 'Categoria'] = 'Optimo'
df.at[6, 'Categoria'] = 'Regular'
df.at[7, 'Categoria'] = 'Estandar'

In [ ]:
print(df['Categoria'])

0      Optimo
1       Bueno
2     Regular
3       Bueno
4    Estandar
5    Estandar
6     Regular
7    Estandar
8     Regular
Name: Categoria, dtype: object

In [ ]:
import pandas as pd
import numpy as np

# 1. Cargar el archivo (ya lo hiciste, pero por si acaso)
#df = pd.read_excel('hecho mas arriba')

# --- ESTADÍSTICAS RÁPIDAS ---
print("--- Resumen estadístico (Promedios, min, max, etc.) ---")
print(df.describe()) # Solo analiza columnas con números

# --- LIMPIEZA DE DATOS ---
# Si tienes celdas vacías (NaN), esto las rellena con un 0 para que no den error
df_limpio = df.fillna(0)

# --- USO DE NUMPY (Cálculos directos) ---
# Supongamos que tienes una columna llamada 'Ventas'
# Sacamos el promedio usando NumPy directamente del DataFrame
promedio_ventas = np.mean(df['Ventas'])
print(f"\nEl promedio de ventas es: {promedio_ventas}")

# --- FILTRADO INTELIGENTE ---
# Ver solo las filas donde las Ventas sean mayores al promedio
ventas_altas = df[df['Ventas'] > promedio_ventas]
print("\nFilas con ventas por encima del promedio:")
display(ventas_altas) # 'display' hace que se vea bonito en Colab

--- Resumen estadístico (Promedios, min, max, etc.) ---
       Customer ID       Order ID        Stock                 Date  \
count     9.000000       9.000000     9.000000                    9
mean      3.444444  607680.333333  1094.333333  2020-03-25 13:20:00
min       1.000000  140794.000000   292.000000  2019-09-01 00:00:00
25%       3.000000  505339.000000   549.000000  2020-02-01 00:00:00
50%       3.000000  684759.000000   883.000000  2020-06-01 00:00:00
75%       5.000000  738711.000000  1006.000000  2020-07-01 00:00:00
max       5.000000  898637.000000  2518.000000  2020-09-01 00:00:00
std       1.424001  260333.556310   833.345517                  NaN

             Ventas         Cost         Neto  Porcentaje_Ganancia
count      9.000000     9.000000     9.000000                 9.00
mean    5681.111111  2188.666667  3492.444444               161.86
min     1460.000000   584.000000   876.000000               150.00
25%     2745.000000  1098.000000  1647.000000               150.00
50%     4870.000000  1766.000000  2922.000000               150.00
75%     6300.000000  2012.000000  4534.000000               150.00
max    12590.000000  5036.000000  7554.000000               256.74
std     4154.331157  1666.691033  2519.169115                35.58

El promedio de ventas es: 5681.111111111111

Filas con ventas por encima del promedio:

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria,Neto,Porcentaje_Ganancia
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular,7554.0,150.00
5,5,889571,Chocolate Caramelo,883,2020-08-01,6300.0,1766,Estandar,4534.0,256.74
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular,7416.0,150.00

In [ ]:
 #Filtrar solo por ventas mayores a 6000
altas_ventas = df[df['Ventas'] > 6000]

print("--- Productos con Ventas > 6000 ---")
display(altas_ventas)

--- Productos con Ventas > 6000 ---

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Categoria,Neto,Porcentaje_Ganancia,Costo
2,3,684759,Chocolate Blanco,2518,2020-06-01,12590.0,5036,Regular,7554.0,150.00,5036
5,5,889571,Chocolate Caramelo,883,2020-08-01,6300.0,1766,Estandar,4534.0,256.74,1766
8,5,703997,Chocolate Con Leche,2472,2020-09-01,12360.0,4944,Regular,7416.0,150.00,4944

In [ ]:
#otra forma de subir un archivo
from google.colab import files
import pandas as pd
subida = files.upload()


import pandas as pd
Nombre_archivo = list(subida.keys())[0]
df=pd.read_excel(Nombre_archivo)
df.head()

In [ ]:
#Otra forma de impotar analisis automatico de datos
import pandas as pd
from ydata_profiling import ProfileReport

In [ ]:
# ESTO SERIA EL PASO N°2
# ESTA FUNCION SIEMPRE COPIAR AL INICIAR "INFORME FINAL VENTAS.xlsx"

def actualizar_todo(dataframe):
    import numpy as np
    # Cálculo de Ventas
    dataframe['Ventas'] = np.where(dataframe['Costo'] > 50000,
                                 dataframe['Costo'] * 1.30,
                                 dataframe['Costo'] * 1.10)

    # Cálculo de Óptimo, Margen y Resultado
    dataframe['Optimo'] = dataframe['Ventas'] * 1.20
    dataframe['Marg_logr'] = ((dataframe['Ventas'] / dataframe['Optimo']) * 100).round(2)
    dataframe['Resultado'] = dataframe['Ventas'] - dataframe['Costo']

    # Re-ordenar (por si agregaste filas nuevas)
    dataframe['temp'] = dataframe.groupby('Vendedor')['Ventas'].transform('sum')
    dataframe.sort_values(by=['temp', 'Vendedor'], ascending=[False, True], inplace=True)

    dataframe.drop(columns=['temp'], inplace=True)
    dataframe.reset_index(drop=True, inplace=True)
    return dataframe

In [ ]:
# Paso N°1
# Esto es para incorporar al colab "Informe Final Ventas.xlsx"
# 1. Conectar con Google Drive
from google.colab import drive
import pandas as pd
import numpy as np

drive.mount('/content/drive')

# 2. Definir la ruta del archivo (ajusta el nombre si es necesario)
ruta = '/content/drive/MyDrive/MisProyectos/Informe_Final_Ventas.xlsx'

# 3. Cargar la tabla
try:
    df = pd.read_excel(ruta, sheet_name='Detalle_Filas')
    print("✅ Archivo cargado correctamente desde Drive")
except:
    print("❌ No se encontró el archivo. Revisa que esté en la carpeta 'MisProyectos'")

# 4. Pegar aquí tu función 'actualizar_todo' (la que ya tienes)
# ... (aquí pegas el def actualizar_todo)

In [ ]:
# Paso 3 Guardar Todo
df_resumen = df.groupby('Vendedor')['Ventas'].sum().reset_index()

# 2. (OPCIONAL) Podemos añadirle un conteo de cuántas ventas hizo cada uno
df_resumen['Cantidad_Operaciones'] = df.groupby('Vendedor')['Ventas'].count().values

# --- AHORA SÍ, EL GUARDADO QUE YA TIENES ---
ruta_drive = '/content/drive/MyDrive/MisProyectos/Informe_Final_Ventas.xlsx'

with pd.ExcelWriter(ruta_drive) as writer:
    df.to_excel(writer, sheet_name='Detalle_Ventas', index=False)
    df_resumen.to_excel(writer, sheet_name='Resumen_Ejecutivo', index=False)

print("🚀 ¡Ahora sí! Resumen creado y guardado en Drive.")

In [ ]:
import matplotlib.pyplot as plt

# 1. Crear el gráfico de ventas por vendedor
plt.figure(figsize=(10,6))
plt.bar(df_resumen['Vendedor'], df_resumen['Ventas'], color='teal')
plt.title('Ranking de Ventas Totales por Vendedor')
plt.xticks(rotation=45)

# 2. GUARDAR el gráfico como imagen directamente en tu Drive
ruta_grafico = '/content/drive/MyDrive/MisProyectos/grafico_ventas.png'
plt.savefig(ruta_grafico, bbox_inches='tight')

# 3. Mostrarlo en pantalla
plt.show()

print(f"✅ Gráfico guardado en: {ruta_grafico}")

In [ ]:
import pandas as pd

def cargar_dataset(link):
    # Extrae el ID y genera el link de descarga directa
    file_id = link.split('/d/')[1].split('/')[0]
    url = f"https://google.com{file_id}"

    # Lee el archivo CSV
    df = pd.read_csv(url)
    return df

In [1]:
import pandas as pd

In [6]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [10]:
df = pd.read_excel('/content/Cookie _Types.xlsx')

In [11]:
df.head(7)

,Cookie Type,Units Sold,Revenue Per Cookie,Cost Per Cookie
0,Chocolate Chip,338239.5,5,2.00
1,Fortune Cookie,154198.0,1,0.50
2,Oatmeal Raisin,155315.0,5,2.20
3,Snickerdoodle,146846.0,4,1.50
4,Sugar,168783.0,3,1.25
5,White Chocolate Macadamia Nut,162424.5,6,2.75

In [13]:
df["Units Sold"].value_counts()

Units Sold
338239.5    1
154198.0    1
155315.0    1
146846.0    1
168783.0    1
162424.5    1
Name: count, dtype: int64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Cookie Type         6 non-null      object
 1   Units Sold          6 non-null      float64
 2   Revenue Per Cookie  6 non-null      int64
 3   Cost Per Cookie     6 non-null      float64
dtypes: float64(2), int64(1), object(1)
memory usage: 324.0+ bytes