<a href="https://colab.research.google.com/github/Betaniadwell/Analisis_De-Datos_2026/blob/main/Mis_Prac_Analisis_de_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PRACTICA 03/04/2027**

# Sección nueva

In [ ]:
from google.colab import files
import pandas as pd

subida = files.upload()

Saving Presup_2026.xlsx to Presup_2026 (2).xlsx

In [ ]:
import pandas as pd
Presup__2026 = list(subida.keys())[0]
df=pd.read_excel(Presup__2026)
df.head()

    Año Naturaleza    Clase Producto  Enero  Febrero  Marzo   Abril
0  2026      Arbol     Ombu     hoja  120.0    120.0   120.0    120
1  2026      Arbol   Alerce  semilla  590.0    590.0   590.0    590
2  2026      Arbol    Sauce     rama  320.0    320.0   320.0    320
3  2026      Arbol   Cipres  bolilla  630.0    630.0   630.0    630
4  2026      Arbol  Moringa  semilla    NaN    360.0     NaN    565

In [ ]:
# para ver el archivo completo
pd.set_option('display.max_rows', None)
df

     Año Naturaleza        Clase   Producto  Enero  Febrero  Marzo   Abril
0   2026      Arbol         Ombu       hoja  120.0    120.0   120.0    120
1   2026      Arbol       Alerce    semilla  590.0    590.0   590.0    590
2   2026      Arbol        Sauce       rama  320.0    320.0   320.0    320
3   2026      Arbol       Cipres    bolilla  630.0    630.0   630.0    630
4   2026      Arbol      Moringa    semilla    NaN    360.0     NaN    565
5   2026      Arbol    Jacaranda       flor    NaN      NaN     NaN    380
6   2026     Planta       Malvon       Flor  150.0    150.0   150.0    150
7   2026     Planta       Jazmin   Escencia  220.0      0.0   220.0    220
8   2026     Planta         Aloe      Savia  320.0    320.0     0.0    320
9   2026     Hierba       Romero   hojuelas  560.0    560.0   560.0    560
10  2026     Hierba  CardMariano   semillas  460.0    460.0   460.0    460
11  2026     Hierba    Citronela  Repelente  300.0    300.0   300.0    300

In [ ]:
import pandas as pd
import numpy as np
df = df.replace('NaN', np.nan)
df

     Año Naturaleza        Clase   Producto  Enero  Febrero  Marzo   Abril
0   2026      Arbol         Ombu       hoja  120.0    120.0   120.0    120
1   2026      Arbol       Alerce    semilla  590.0    590.0   590.0    590
2   2026      Arbol        Sauce       rama  320.0    320.0   320.0    320
3   2026      Arbol       Cipres    bolilla  630.0    630.0   630.0    630
4   2026      Arbol      Moringa    semilla    NaN    360.0     NaN    565
5   2026      Arbol    Jacaranda       flor    NaN      NaN     NaN    380
6   2026     Planta       Malvon       Flor  150.0    150.0   150.0    150
7   2026     Planta       Jazmin   Escencia  220.0      0.0   220.0    220
8   2026     Planta         Aloe      Savia  320.0    320.0     0.0    320
9   2026     Hierba       Romero   hojuelas  560.0    560.0   560.0    560
10  2026     Hierba  CardMariano   semillas  460.0    460.0   460.0    460
11  2026     Hierba    Citronela  Repelente  300.0    300.0   300.0    300

In [ ]:
#completar con 0 los espacios dejados por NaN
df = df.fillna(0)
df

     Año Naturaleza        Clase   Producto  Enero  Febrero  Marzo   Abril
0   2026      Arbol         Ombu       hoja  120.0    120.0   120.0    120
1   2026      Arbol       Alerce    semilla  590.0    590.0   590.0    590
2   2026      Arbol        Sauce       rama  320.0    320.0   320.0    320
3   2026      Arbol       Cipres    bolilla  630.0    630.0   630.0    630
4   2026      Arbol      Moringa    semilla    0.0    360.0     0.0    565
5   2026      Arbol    Jacaranda       flor    0.0      0.0     0.0    380
6   2026     Planta       Malvon       Flor  150.0    150.0   150.0    150
7   2026     Planta       Jazmin   Escencia  220.0      0.0   220.0    220
8   2026     Planta         Aloe      Savia  320.0    320.0     0.0    320
9   2026     Hierba       Romero   hojuelas  560.0    560.0   560.0    560
10  2026     Hierba  CardMariano   semillas  460.0    460.0   460.0    460
11  2026     Hierba    Citronela  Repelente  300.0    300.0   300.0    300

In [ ]:
# revisa tipeo columnas
print(df.columns.tolist())

['Año', 'Naturaleza', 'Clase', 'Producto', 'Enero', 'Febrero', 'Marzo ', 'Abril']

In [ ]:
#definimos nombres correctos
nuevos_nombres = ['Año', 'Naturaleza', 'Clase', 'Producto', 'Enero', 'Febrero', 'Marzo', 'Abril']
#Se los asignamos al DataFrame (asegúrate que la lista tenga el mismo largo que tus columnas)
df.columns = nuevos_nombres

# Ahora sí, intentamos la conversión a numérico
cols_meses = ['Enero', 'Febrero', 'Marzo', 'Abril']
df[cols_meses] = df[cols_meses].apply(pd.to_numeric, errors='coerce')

#verificamos
df.head()

    Año Naturaleza    Clase Producto  Enero  Febrero  Marzo  Abril
0  2026      Arbol     Ombu     hoja  120.0    120.0  120.0    120
1  2026      Arbol   Alerce  semilla  590.0    590.0  590.0    590
2  2026      Arbol    Sauce     rama  320.0    320.0  320.0    320
3  2026      Arbol   Cipres  bolilla  630.0    630.0  630.0    630
4  2026      Arbol  Moringa  semilla    0.0    360.0    0.0    565

In [ ]:
#Ahora pasamos todo a numerico
# Definimos las columnas de los meses
meses = ['Enero', 'Febrero', 'Marzo', 'Abril']

# Las pasamos todas a entero (int) para que se vean iguales y sin el .0
df[meses] = df[meses].astype(int)

# Ahora probamos un cálculo rápido: Suma total por fila
df['Total'] = df[meses].sum(axis=1)

df.head()

    Año Naturaleza    Clase Producto  Enero  Febrero  Marzo  Abril  Total
0  2026      Arbol     Ombu     hoja    120      120    120    120    480
1  2026      Arbol   Alerce  semilla    590      590    590    590   2360
2  2026      Arbol    Sauce     rama    320      320    320    320   1280
3  2026      Arbol   Cipres  bolilla    630      630    630    630   2520
4  2026      Arbol  Moringa  semilla      0      360      0    565    925

In [ ]:
# 1. Definimos cuáles son las columnas que NO queremos mover (las fijas)
columnas_fijas = ['Año', 'Naturaleza', 'Clase', 'Producto']
columnas_meses = ['Enero', 'Febrero', 'Marzo', 'Abril'] #las movibles
# 2. Aplicamos el "Unpivot" (melt)
df_final = df.melt(
    id_vars=columnas_fijas,     # Las columnas que se quedan quietas
    value_vars=columnas_meses, # Las que se vuelven filas
    var_name='Meses',           # El nombre para la columna de títulos
    value_name='Estimado'       # El nombre para la columna de los montos
)

# 3. Verificamos el resultado
print(df_final)

     Año Naturaleza        Clase   Producto    Meses  Estimado
0   2026      Arbol         Ombu       hoja    Enero       120
1   2026      Arbol       Alerce    semilla    Enero       590
2   2026      Arbol        Sauce       rama    Enero       320
3   2026      Arbol       Cipres    bolilla    Enero       630
4   2026      Arbol      Moringa    semilla    Enero         0
5   2026      Arbol    Jacaranda       flor    Enero         0
6   2026     Planta       Malvon       Flor    Enero       150
7   2026     Planta       Jazmin   Escencia    Enero       220
8   2026     Planta         Aloe      Savia    Enero       320
9   2026     Hierba       Romero   hojuelas    Enero       560
10  2026     Hierba  CardMariano   semillas    Enero       460
11  2026     Hierba    Citronela  Repelente    Enero       300
12  2026      Arbol         Ombu       hoja  Febrero       120
13  2026      Arbol       Alerce    semilla  Febrero       590
14  2026      Arbol        Sauce       rama  Febrero       320
15  2026      Arbol       Cipres    bolilla  Febrero       630
16  2026      Arbol      Moringa    semilla  Febrero       360
17  2026      Arbol    Jacaranda       flor  Febrero         0
18  2026     Planta       Malvon       Flor  Febrero       150
19  2026     Planta       Jazmin   Escencia  Febrero         0
20  2026     Planta         Aloe      Savia  Febrero       320
21  2026     Hierba       Romero   hojuelas  Febrero       560
22  2026     Hierba  CardMariano   semillas  Febrero       460
23  2026     Hierba    Citronela  Repelente  Febrero       300
24  2026      Arbol         Ombu       hoja    Marzo       120
25  2026      Arbol       Alerce    semilla    Marzo       590
26  2026      Arbol        Sauce       rama    Marzo       320
27  2026      Arbol       Cipres    bolilla    Marzo       630
28  2026      Arbol      Moringa    semilla    Marzo         0
29  2026      Arbol    Jacaranda       flor    Marzo         0
30  2026     Planta       Malvon       Flor    Marzo       150
31  2026     Planta       Jazmin   Escencia    Marzo       220
32  2026     Planta         Aloe      Savia    Marzo         0
33  2026     Hierba       Romero   hojuelas    Marzo       560
34  2026     Hierba  CardMariano   semillas    Marzo       460
35  2026     Hierba    Citronela  Repelente    Marzo       300
36  2026      Arbol         Ombu       hoja    Abril       120
37  2026      Arbol       Alerce    semilla    Abril       590
38  2026      Arbol        Sauce       rama    Abril       320
39  2026      Arbol       Cipres    bolilla    Abril       630
40  2026      Arbol      Moringa    semilla    Abril       565
41  2026      Arbol    Jacaranda       flor    Abril       380
42  2026     Planta       Malvon       Flor    Abril       150
43  2026     Planta       Jazmin   Escencia    Abril       220
44  2026     Planta         Aloe      Savia    Abril       320
45  2026     Hierba       Romero   hojuelas    Abril       560
46  2026     Hierba  CardMariano   semillas    Abril       460
47  2026     Hierba    Citronela  Repelente    Abril       300

In [ ]:
df_final['Estimado'][4] = 387
df_final

In [ ]:

df_final['Total'] = df_final['Estimado'].sum()
df_final

     Año Naturaleza        Clase   Producto    Meses  Estimado  Total
0   2026      Arbol         Ombu       hoja    Enero       120  15832
1   2026      Arbol       Alerce    semilla    Enero       590  15832
2   2026      Arbol        Sauce       rama    Enero       320  15832
3   2026      Arbol       Cipres    bolilla    Enero       630  15832
4   2026      Arbol      Moringa    semilla    Enero       387  15832
5   2026      Arbol    Jacaranda       flor    Enero         0  15832
6   2026     Planta       Malvon       Flor    Enero       150  15832
7   2026     Planta       Jazmin   Escencia    Enero       220  15832
8   2026     Planta         Aloe      Savia    Enero       320  15832
9   2026     Hierba       Romero   hojuelas    Enero       560  15832
10  2026     Hierba  CardMariano   semillas    Enero       460  15832
11  2026     Hierba    Citronela  Repelente    Enero       300  15832
12  2026      Arbol         Ombu       hoja  Febrero       120  15832
13  2026      Arbol       Alerce    semilla  Febrero       590  15832
14  2026      Arbol        Sauce       rama  Febrero       320  15832
15  2026      Arbol       Cipres    bolilla  Febrero       630  15832
16  2026      Arbol      Moringa    semilla  Febrero       360  15832
17  2026      Arbol    Jacaranda       flor  Febrero         0  15832
18  2026     Planta       Malvon       Flor  Febrero       150  15832
19  2026     Planta       Jazmin   Escencia  Febrero         0  15832
20  2026     Planta         Aloe      Savia  Febrero       320  15832
21  2026     Hierba       Romero   hojuelas  Febrero       560  15832
22  2026     Hierba  CardMariano   semillas  Febrero       460  15832
23  2026     Hierba    Citronela  Repelente  Febrero       300  15832
24  2026      Arbol         Ombu       hoja    Marzo       120  15832
25  2026      Arbol       Alerce    semilla    Marzo       590  15832
26  2026      Arbol        Sauce       rama    Marzo       320  15832
27  2026      Arbol       Cipres    bolilla    Marzo       630  15832
28  2026      Arbol      Moringa    semilla    Marzo         0  15832
29  2026      Arbol    Jacaranda       flor    Marzo         0  15832
30  2026     Planta       Malvon       Flor    Marzo       150  15832
31  2026     Planta       Jazmin   Escencia    Marzo       220  15832
32  2026     Planta         Aloe      Savia    Marzo         0  15832
33  2026     Hierba       Romero   hojuelas    Marzo       560  15832
34  2026     Hierba  CardMariano   semillas    Marzo       460  15832
35  2026     Hierba    Citronela  Repelente    Marzo       300  15832
36  2026      Arbol         Ombu       hoja    Abril       120  15832
37  2026      Arbol       Alerce    semilla    Abril       590  15832
38  2026      Arbol        Sauce       rama    Abril       320  15832
39  2026      Arbol       Cipres    bolilla    Abril       630  15832
40  2026      Arbol      Moringa    semilla    Abril       565  15832
41  2026      Arbol    Jacaranda       flor    Abril       380  15832
42  2026     Planta       Malvon       Flor    Abril       150  15832
43  2026     Planta       Jazmin   Escencia    Abril       220  15832
44  2026     Planta         Aloe      Savia    Abril       320  15832
45  2026     Hierba       Romero   hojuelas    Abril       560  15832
46  2026     Hierba  CardMariano   semillas    Abril       460  15832
47  2026     Hierba    Citronela  Repelente    Abril       300  15832

In [ ]:
df_final = df_final.drop(columns=['Total'])
print(df_final)

     Año Naturaleza        Clase   Producto    Meses
0   2026      Arbol         Ombu       hoja    Enero
1   2026      Arbol       Alerce    semilla    Enero
2   2026      Arbol        Sauce       rama    Enero
3   2026      Arbol       Cipres    bolilla    Enero
4   2026      Arbol      Moringa    semilla    Enero
5   2026      Arbol    Jacaranda       flor    Enero
6   2026     Planta       Malvon       Flor    Enero
7   2026     Planta       Jazmin   Escencia    Enero
8   2026     Planta         Aloe      Savia    Enero
9   2026     Hierba       Romero   hojuelas    Enero
10  2026     Hierba  CardMariano   semillas    Enero
11  2026     Hierba    Citronela  Repelente    Enero
12  2026      Arbol         Ombu       hoja  Febrero
13  2026      Arbol       Alerce    semilla  Febrero
14  2026      Arbol        Sauce       rama  Febrero
15  2026      Arbol       Cipres    bolilla  Febrero
16  2026      Arbol      Moringa    semilla  Febrero
17  2026      Arbol    Jacaranda       flor  Febrero
18  2026     Planta       Malvon       Flor  Febrero
19  2026     Planta       Jazmin   Escencia  Febrero
20  2026     Planta         Aloe      Savia  Febrero
21  2026     Hierba       Romero   hojuelas  Febrero
22  2026     Hierba  CardMariano   semillas  Febrero
23  2026     Hierba    Citronela  Repelente  Febrero
24  2026      Arbol         Ombu       hoja    Marzo
25  2026      Arbol       Alerce    semilla    Marzo
26  2026      Arbol        Sauce       rama    Marzo
27  2026      Arbol       Cipres    bolilla    Marzo
28  2026      Arbol      Moringa    semilla    Marzo
29  2026      Arbol    Jacaranda       flor    Marzo
30  2026     Planta       Malvon       Flor    Marzo
31  2026     Planta       Jazmin   Escencia    Marzo
32  2026     Planta         Aloe      Savia    Marzo
33  2026     Hierba       Romero   hojuelas    Marzo
34  2026     Hierba  CardMariano   semillas    Marzo
35  2026     Hierba    Citronela  Repelente    Marzo
36  2026      Arbol         Ombu       hoja    Abril
37  2026      Arbol       Alerce    semilla    Abril
38  2026      Arbol        Sauce       rama    Abril
39  2026      Arbol       Cipres    bolilla    Abril
40  2026      Arbol      Moringa    semilla    Abril
41  2026      Arbol    Jacaranda       flor    Abril
42  2026     Planta       Malvon       Flor    Abril
43  2026     Planta       Jazmin   Escencia    Abril
44  2026     Planta         Aloe      Savia    Abril
45  2026     Hierba       Romero   hojuelas    Abril
46  2026     Hierba  CardMariano   semillas    Abril
47  2026     Hierba    Citronela  Repelente    Abril

In [ ]:
importes=['230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910','230','150','560','910']
df_final['Estimado'] = importes
df_final['Estimado'] = pd.to_numeric(df_final['Estimado'])#corrige '230'......sin ''
pd.set_option('display.max_rows', None) # Muestra todas las filas
df_final

     Año Naturaleza        Clase   Producto    Meses  Estimado
0   2026      Arbol         Ombu       hoja    Enero       230
1   2026      Arbol       Alerce    semilla    Enero       150
2   2026      Arbol        Sauce       rama    Enero       560
3   2026      Arbol       Cipres    bolilla    Enero       910
4   2026      Arbol      Moringa    semilla    Enero       230
5   2026      Arbol    Jacaranda       flor    Enero       150
6   2026     Planta       Malvon       Flor    Enero       560
7   2026     Planta       Jazmin   Escencia    Enero       910
8   2026     Planta         Aloe      Savia    Enero       230
9   2026     Hierba       Romero   hojuelas    Enero       150
10  2026     Hierba  CardMariano   semillas    Enero       560
11  2026     Hierba    Citronela  Repelente    Enero       910
12  2026      Arbol         Ombu       hoja  Febrero       230
13  2026      Arbol       Alerce    semilla  Febrero       150
14  2026      Arbol        Sauce       rama  Febrero       560
15  2026      Arbol       Cipres    bolilla  Febrero       910
16  2026      Arbol      Moringa    semilla  Febrero       230
17  2026      Arbol    Jacaranda       flor  Febrero       150
18  2026     Planta       Malvon       Flor  Febrero       560
19  2026     Planta       Jazmin   Escencia  Febrero       910
20  2026     Planta         Aloe      Savia  Febrero       230
21  2026     Hierba       Romero   hojuelas  Febrero       150
22  2026     Hierba  CardMariano   semillas  Febrero       560
23  2026     Hierba    Citronela  Repelente  Febrero       910
24  2026      Arbol         Ombu       hoja    Marzo       230
25  2026      Arbol       Alerce    semilla    Marzo       150
26  2026      Arbol        Sauce       rama    Marzo       560
27  2026      Arbol       Cipres    bolilla    Marzo       910
28  2026      Arbol      Moringa    semilla    Marzo       230
29  2026      Arbol    Jacaranda       flor    Marzo       150
30  2026     Planta       Malvon       Flor    Marzo       560
31  2026     Planta       Jazmin   Escencia    Marzo       910
32  2026     Planta         Aloe      Savia    Marzo       230
33  2026     Hierba       Romero   hojuelas    Marzo       150
34  2026     Hierba  CardMariano   semillas    Marzo       560
35  2026     Hierba    Citronela  Repelente    Marzo       910
36  2026      Arbol         Ombu       hoja    Abril       230
37  2026      Arbol       Alerce    semilla    Abril       150
38  2026      Arbol        Sauce       rama    Abril       560
39  2026      Arbol       Cipres    bolilla    Abril       910
40  2026      Arbol      Moringa    semilla    Abril       230
41  2026      Arbol    Jacaranda       flor    Abril       150
42  2026     Planta       Malvon       Flor    Abril       560
43  2026     Planta       Jazmin   Escencia    Abril       910
44  2026     Planta         Aloe      Savia    Abril       230
45  2026     Hierba       Romero   hojuelas    Abril       150
46  2026     Hierba  CardMariano   semillas    Abril       560
47  2026     Hierba    Citronela  Repelente    Abril       910

In [ ]:
df__prueba = df_final.copy()

In [ ]:
hecho con una copia por las dudas no aruinar la tabla y sin regreso




Ahora: Con return fila['Estimado'] * 1.20, le estás diciendo:
"Toma el número de esta fila específica, multiplícalo por 1.20 y devuélveme solo ese resultado".
def mi_logica(fila):

    if fila['Estimado'] > 10 :
        return fila['Estimado'] * 1.20

    else:
        return 0

df__prueba['Descuento']= df__prueba.apply(lambda x:mi_logica(x), axis=1)
print(df__prueba)

     Año Naturaleza        Clase   Producto    Meses  Estimado  Descuento
0   2026      Arbol         Ombu       hoja    Enero       230      276.0
1   2026      Arbol       Alerce    semilla    Enero       150      180.0
2   2026      Arbol        Sauce       rama    Enero       560      672.0
3   2026      Arbol       Cipres    bolilla    Enero       910     1092.0
4   2026      Arbol      Moringa    semilla    Enero       230      276.0
5   2026      Arbol    Jacaranda       flor    Enero       150      180.0
6   2026     Planta       Malvon       Flor    Enero       560      672.0
7   2026     Planta       Jazmin   Escencia    Enero       910     1092.0
8   2026     Planta         Aloe      Savia    Enero       230      276.0
9   2026     Hierba       Romero   hojuelas    Enero       150      180.0
10  2026     Hierba  CardMariano   semillas    Enero       560      672.0
11  2026     Hierba    Citronela  Repelente    Enero       910     1092.0
12  2026      Arbol         Ombu       hoja  Febrero       230      276.0
13  2026      Arbol       Alerce    semilla  Febrero       150      180.0
14  2026      Arbol        Sauce       rama  Febrero       560      672.0
15  2026      Arbol       Cipres    bolilla  Febrero       910     1092.0
16  2026      Arbol      Moringa    semilla  Febrero       230      276.0
17  2026      Arbol    Jacaranda       flor  Febrero       150      180.0
18  2026     Planta       Malvon       Flor  Febrero       560      672.0
19  2026     Planta       Jazmin   Escencia  Febrero       910     1092.0
20  2026     Planta         Aloe      Savia  Febrero       230      276.0
21  2026     Hierba       Romero   hojuelas  Febrero       150      180.0
22  2026     Hierba  CardMariano   semillas  Febrero       560      672.0
23  2026     Hierba    Citronela  Repelente  Febrero       910     1092.0
24  2026      Arbol         Ombu       hoja    Marzo       230      276.0
25  2026      Arbol       Alerce    semilla    Marzo       150      180.0
26  2026      Arbol        Sauce       rama    Marzo       560      672.0
27  2026      Arbol       Cipres    bolilla    Marzo       910     1092.0
28  2026      Arbol      Moringa    semilla    Marzo       230      276.0
29  2026      Arbol    Jacaranda       flor    Marzo       150      180.0
30  2026     Planta       Malvon       Flor    Marzo       560      672.0
31  2026     Planta       Jazmin   Escencia    Marzo       910     1092.0
32  2026     Planta         Aloe      Savia    Marzo       230      276.0
33  2026     Hierba       Romero   hojuelas    Marzo       150      180.0
34  2026     Hierba  CardMariano   semillas    Marzo       560      672.0
35  2026     Hierba    Citronela  Repelente    Marzo       910     1092.0
36  2026      Arbol         Ombu       hoja    Abril       230      276.0
37  2026      Arbol       Alerce    semilla    Abril       150      180.0
38  2026      Arbol        Sauce       rama    Abril       560      672.0
39  2026      Arbol       Cipres    bolilla    Abril       910     1092.0
40  2026      Arbol      Moringa    semilla    Abril       230      276.0
41  2026      Arbol    Jacaranda       flor    Abril       150      180.0
42  2026     Planta       Malvon       Flor    Abril       560      672.0
43  2026     Planta       Jazmin   Escencia    Abril       910     1092.0
44  2026     Planta         Aloe      Savia    Abril       230      276.0
45  2026     Hierba       Romero   hojuelas    Abril       150      180.0
46  2026     Hierba  CardMariano   semillas    Abril       560      672.0
47  2026     Hierba    Citronela  Repelente    Abril       910     1092.0

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_prueba = df_prueba.assign(Revicion) = Procesando

In [ ]:
df__prueba.at[1, 'Descuento'] = 185

df__prueba

In [ ]:
df__prueba['Revision']= df__prueba['Descuento'].apply(lambda x: x * 1,50 )
print(df)

In [ ]:
from google.colab import files
import pandas as pd

subida = files.upload()

Saving Orders.xlsx to Orders (1).xlsx

In [ ]:
Orders = list(subida.keys())[0]
import pandas as pd
df=pd.read_excel(Orders)
df

   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost
0            3    266868  Chocolate Chip    292 2020-02-01    1460   584
1            3    140794  Chocolate Chip    974 2020-02-01    4870  1948
2            3    684759  Chocolate Chip   2518 2020-06-01   12590  5036
3            4    640447  Chocolate Chip   1006 2020-06-01    5030  2012
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

In [ ]:
pd.set_option('display.max_rows', None)
df

   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost
0            3    266868  Chocolate Chip    292 2020-02-01    1460   584
1            3    140794  Chocolate Chip    974 2020-02-01    4870  1948
2            3    684759  Chocolate Chip   2518 2020-06-01   12590  5036
3            4    640447  Chocolate Chip   1006 2020-06-01    5030  2012
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

In [ ]:
# cantidad de filas y las ultimas 5 filas
print(len(df))
print(df.tail(5)) # Fuerza a mostrar las últimas 5 filas

9
   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

In [ ]:
def mi_logica(fila):

    if fila['Ventas'] > 2000 :
        return fila['Ventas'] * 1.30

    else:
        return fila['Ventas'] * 1.10

df['Descuento']= df.apply(lambda x:mi_logica(x), axis=1)
print(df)

   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost  \
0            3    266868  Chocolate Chip    292 2020-02-01    1460   584
1            3    140794  Chocolate Chip    974 2020-02-01    4870  1948
2            3    684759  Chocolate Chip   2518 2020-06-01   12590  5036
3            4    640447  Chocolate Chip   1006 2020-06-01    5030  2012
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

   Descuento
0     1606.0
1     6331.0
2    16367.0
3     6539.0
4     2018.5
5     5739.5
6     3568.5
7     5122.0
8    16068.0

In [ ]:
df['Impuesto']= df['Descuento'].apply(lambda x: x * 0.15). round(2)
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20

In [ ]:
import numpy as np

Importes=['230','150','560','910','230','150','560','910','230']
df['Estimado'] = Importes
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto,Estimado
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90,230
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65,150
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05,560
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85,910
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78,230
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92,150
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28,560
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30,910
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20,230

In [ ]:
df = df.drop(columns=['Estimado'])
print(df)

   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost  \
0            3    266868  Chocolate Chip    292 2020-02-01    1460   584
1            3    140794  Chocolate Chip    974 2020-02-01    4870  1948
2            3    684759  Chocolate Chip   2518 2020-06-01   12590  5036
3            4    640447  Chocolate Chip   1006 2020-06-01    5030  2012
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

   Descuento  Impuesto
0     1606.0    240.90
1     6331.0    949.65
2    16367.0   2455.05
3     6539.0    980.85
4     2018.5    302.78
5     5739.5    860.92
6     3568.5    535.28
7     5122.0    768.30
8    16068.0   2410.20

In [ ]:
df['nuevos_precios']= df['Cost'].apply(lambda x: x * 1.10 if x > 2000 else x * 1.50)
print(df)

   Customer ID  Order ID         Product  Stock       Date  Ventas  Cost  \
0            3    266868  Chocolate Chip    292 2020-02-01    1460   584
1            3    140794  Chocolate Chip    974 2020-02-01    4870  1948
2            3    684759  Chocolate Chip   2518 2020-06-01   12590  5036
3            4    640447  Chocolate Chip   1006 2020-06-01    5030  2012
4            2    898637  Chocolate Chip    367 2020-07-01    1835   734
5            5    889571  Chocolate Chip    883 2020-08-01    4415  1766
6            1    738711  Chocolate Chip    549 2019-09-01    2745  1098
7            5    505339  Chocolate Chip    788 2019-09-01    3940  1576
8            5    703997  Chocolate Chip   2472 2020-09-01   12360  4944

   Descuento  Impuesto  nuevos_precios
0     1606.0    240.90           876.0
1     6331.0    949.65          2922.0
2    16367.0   2455.05          5539.6
3     6539.0    980.85          2213.2
4     2018.5    302.78          1101.0
5     5739.5    860.92          2649.0
6     3568.5    535.28          1647.0
7     5122.0    768.30          2364.0
8    16068.0   2410.20          5438.4

In [ ]:
df['Sin_Numero'] ='Nan'
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto,nuevos_precios,Sin_Numero
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90,876.0,Nan
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65,2922.0,Nan
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05,5539.6,Nan
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85,2213.2,Nan
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78,1101.0,Nan
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92,2649.0,Nan
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28,1647.0,Nan
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30,2364.0,Nan
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20,5438.4,Nan

In [ ]:
df = df.replace('Nan', np.nan)
df

/tmp/ipykernel_8523/2828676074.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('Nan', np.nan)

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto,nuevos_precios,Sin_Numero
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90,876.0,NaN
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65,2922.0,NaN
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05,5539.6,NaN
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85,2213.2,NaN
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78,1101.0,NaN
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92,2649.0,NaN
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28,1647.0,NaN
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30,2364.0,NaN
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20,5438.4,NaN

In [ ]:
df = df.fillna(0)
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto,nuevos_precios,Sin_Numero
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90,876.0,0.0
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65,2922.0,0.0
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05,5539.6,0.0
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85,2213.2,0.0
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78,1101.0,0.0
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92,2649.0,0.0
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28,1647.0,0.0
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30,2364.0,0.0
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20,5438.4,0.0

In [ ]:
#cambiar nombre de columna
df = df.rename(columns={'Sin_Numero': 'Disponible'})

# 2. Llenar toda la columna con el número 1
df['Disponible'] = 1
df

,Customer ID,Order ID,Product,Stock,Date,Ventas,Cost,Descuento,Impuesto,nuevos_precios,Disponible
0,3,266868,Chocolate Chip,292,2020-02-01,1460,584,1606.0,240.90,876.0,1
1,3,140794,Chocolate Chip,974,2020-02-01,4870,1948,6331.0,949.65,2922.0,1
2,3,684759,Chocolate Chip,2518,2020-06-01,12590,5036,16367.0,2455.05,5539.6,1
3,4,640447,Chocolate Chip,1006,2020-06-01,5030,2012,6539.0,980.85,2213.2,1
4,2,898637,Chocolate Chip,367,2020-07-01,1835,734,2018.5,302.78,1101.0,1
5,5,889571,Chocolate Chip,883,2020-08-01,4415,1766,5739.5,860.92,2649.0,1
6,1,738711,Chocolate Chip,549,2019-09-01,2745,1098,3568.5,535.28,1647.0,1
7,5,505339,Chocolate Chip,788,2019-09-01,3940,1576,5122.0,768.30,2364.0,1
8,5,703997,Chocolate Chip,2472,2020-09-01,12360,4944,16068.0,2410.20,5438.4,1

In [ ]:
nombres_columnas = df.columns.tolist()

print(nombres_columnas)

['Customer ID', 'Order ID', 'Product', 'Stock', 'Date', 'Ventas', 'Cost', 'Descuento', 'Impuesto', 'nuevos_precios', 'Disponible']

In [ ]:
df.columns = df.columns.str.strip()
df.columns = [str(col).strip() for col in df.columns]
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
#unpivot
columnas_fijas = ['Customer ID', 'Order ID', 'Product', 'Stock','Date']
columnas_meses = ['Ventas', 'Cost', 'Descuento', 'Impuesto','nuevos_precios','Disponible'] #las movibles2. Aplicamos el "Unpivot" (melt)
df= df.melt(
    id_vars=columnas_fijas,     # Las columnas que se quedan quietas
    value_vars=columnas_meses, # Las que se vuelven filas
    var_name='Evento',           # El nombre para la columna de títulos
    value_name='Importe'       # El nombre para la columna de los montos
)

print(df)