In [ ]:
from numpy import nanquantile
import pandas as pd
cuentas=[16.99,10.34,87.26,25.59,12.20,91.21,56.89]

cuentas.append(19.74)
cuentas.pop(0)
cuentas.remove(56.89)
del cuentas[3]

print(cuentas)
df=pd.DataFrame(cuentas)

#elimina empezando por el indice que nesecito
df = df[df.index <= 30]

df = df.drop(df[df.index > 50].index)
print(df)

df = df[df <= 50]
df = df[df < 50].dropna()
print(df)

       0
0  16.99
1  10.34
3  25.59
4  12.20

Sintaxis: df.loc[nombre_fila, nombre_columna]


Sintaxis: df.iloc[numero_fila, numero_columna]

In [ ]:
df = df.reset_index(drop=True)
print (df)
# vuelve a insertar el indice 2

       0
0  16.99
1  10.34
2  25.59
3  12.20

In [ ]:
df.iloc[2, 0] = 39.66
print(df)

       0
0  16.99
1  10.34
2  39.66
3  12.20

In [ ]:
df = df.drop(3)
print(df)

In [ ]:
df.insert(1, 'Nuevo', [18.23, 15.63, 96.20])
print(df)

In [ ]:

#otras formas de inserta columna si quiero que se agregue al final

df['Nueva_Columna'] = [100, 200, 300]
# o tambien
df = df.assign(Total = [50, 60, 70])

In [ ]:
import numpy as np

In [ ]:
# Declaramos un diccionario de tips
tips = {
    "total_cuenta": [16.99, 10.34, 21.01]
}
tips

{'total_cuenta': [16.99, 10.34, 21.01]}

In [ ]:
tips["propina"] = [1.01, 1.66, 3.5]
tips

{'total_cuenta': [16.99, 10.34, 21.01], 'propina': [1.01, 1.66, 3.5]}

In [ ]:
df=pd.DataFrame(tips)
print(df)

   total_cuenta  propina
0         16.99     1.01
1         10.34     1.66
2         21.01     3.50

In [ ]:
df['propinas_ars']= df['propina'].apply(lambda x: x * 1500 )
print(df)

   total_cuenta  propina  propindfas_ars  propinas_ars
0         16.99     1.01          1515.0        1515.0
1         10.34     1.66          2490.0        2490.0
2         21.01     3.50          5250.0        5250.0

In [ ]:
import numpy as np

In [ ]:
df

   total_cuenta  propina  propindfas_ars  propinas_ars
0         16.99     1.01          1515.0        1515.0
1         10.34     1.66          2490.0        2490.0
2         21.01     3.50          5250.0        5250.0

In [ ]:
import pandas as pd

In [ ]:
from numpy import nanquantile
import pandas as pd
datos = {'A': 16.99, 'B': 10.34, 'C': 87.26, 'D': 25.59}

# Creamos el DataFrame usando el diccionario como INDEX
df = pd.DataFrame.from_dict(datos, orient='index', columns=['Precio'])
print("DataFrame original:")
print(df)
df = df.drop('A')
print(df)
df= df.iloc[0]
print(df)

DataFrame original:
   Precio
A   16.99
B   10.34
C   87.26
D   25.59
Precio    16.99
Name: A, dtype: float64

In [ ]:
from numpy import nanquantile
import pandas as pd

datos = {'A': 16.99, 'B': 10.34, 'C': 87.26, 'D': 25.59}
df= pd.DataFrame.from_dict(datos, orient='index', columns=['Precio'])
print(df)
#elimino los datos de la columna
colum_ext = df.pop('Precio')
print (df)

   Precio
A   16.99
B   10.34
C   87.26
D   25.59
Empty DataFrame
Columns: []
Index: [A, B, C, D]

In [ ]:
df = df.assign(Costo = [50, 60, 70, 36],Detalles =['Azucar','Cafe','Lentejas','vinos'],Inventario=[630, 960, 874, 1260])
print(df)
val_col=df.pop('Costo')
print(df)

In [ ]:
from numpy import nanquantile
import pandas as pd

datos = {'A': 16.99, 'B': 10.34, 'C': 87.26, 'D': 25.59}
df= pd.DataFrame.from_dict(datos, orient='index', columns=['Precio'])
df = df.assign(Costo = [50, 60, 70, 36],Detalles =['Azucar','Cafe','Lentejas','vinos'],Inventario=[630, 960, 874, 1260])
print(df)


df['Nueva']= df['Costo'].apply(lambda x: x * 1.10 if x > 51 else x * 1.50)
print(df)

df = df.assign(Estado=['Optimo','a_vencer','Medio','Optimo'])
print(df)

   Precio  Costo  Detalles  Inventario
A   16.99     50    Azucar         630
B   10.34     60      Cafe         960
C   87.26     70  Lentejas         874
D   25.59     36     vinos        1260
   Precio  Costo  Detalles  Inventario  Nueva
A   16.99     50    Azucar         630   75.0
B   10.34     60      Cafe         960   66.0
C   87.26     70  Lentejas         874   77.0
D   25.59     36     vinos        1260   54.0
   Precio  Costo  Detalles  Inventario  Nueva    Estado
A   16.99     50    Azucar         630   75.0    Optimo
B   10.34     60      Cafe         960   66.0  a_vencer
C   87.26     70  Lentejas         874   77.0     Medio
D   25.59     36     vinos        1260   54.0    Optimo

In [ ]:
import pandas as pd

# Usamos la ruta exacta que te dio Colab
ruta_excel = '/tips.xlsx'

try:
    # OJO: Para Excel se usa read_excel, no read_csv
    df = pd.read_excel(ruta_excel)

    print("¡LOGRADO! Leímos el Excel:")
    display(df.head())

    # Creamos la columna nueva para practicar
    df['Nueva'] = df['tip'] * 1.5
    display(df.head())

except Exception as e:
    print(f"Error: {e}")
    print("Si te dice que falta 'openpyxl', corre en una celda: !pip install openpyxl")

¡LOGRADO! Leímos el Excel:

,total_bill,tip,sex,smoker,day,time,size,Unnamed: 7,Columnas = Variables
0,50.81,10.0,Male,Yes,Sat,Dinner,3,NaN,Filas = Observaciones
1,48.33,9.0,Male,No,Sat,Dinner,4,NaN,NaN
2,48.27,6.73,Male,No,Sat,Dinner,4,NaN,NaN
3,48.17,5.0,Male,No,Sun,Dinner,6,NaN,NaN
4,45.35,2026-05-03 00:00:00,Male,Yes,Sun,Dinner,3,NaN,NaN

Error: can't multiply sequence by non-int of type 'float'
Si te dice que falta 'openpyxl', corre en una celda: !pip install openpyxl

In [ ]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd

# 1. Volvemos a leer el archivo original para recuperar los datos
df = pd.read_excel('/tips.xlsx')

# 2. En lugar de borrar todo, borramos SOLO las columnas que están totalmente vacías
df = df.dropna(axis=1, how='all')

# 3. Si todavía ves NaNs, los llenamos con 0 para que no desaparezcan las filas
df = df.fillna(0)

print("¡Datos recuperados y limpios!")
display(df.head())

¡Datos recuperados y limpios!

,total_bill,tip,sex,smoker,day,time,size,Columnas = Variables
0,50.81,10.0,Male,Yes,Sat,Dinner,3,Filas = Observaciones
1,48.33,9.0,Male,No,Sat,Dinner,4,0
2,48.27,6.73,Male,No,Sat,Dinner,4,0
3,48.17,5.0,Male,No,Sun,Dinner,6,0
4,45.35,2026-05-03 00:00:00,Male,Yes,Sun,Dinner,3,0

In [ ]:
df.at[4, 'tip'] = 2.50
display(df.head())

   total_bill   tip   sex smoker  day    time  size   Columnas = Variables
0       50.81  10.0  Male    Yes  Sat  Dinner     3  Filas = Observaciones
1       48.33   9.0  Male     No  Sat  Dinner     4                      0
2       48.27  6.73  Male     No  Sat  Dinner     4                      0
3       48.17   5.0  Male     No  Sun  Dinner     6                      0
4       45.35   2.5  Male    Yes  Sun  Dinner     3                      0

In [ ]:
#convierte la columna en tipo numerico
df['tip'] = pd.to_numeric(df['tip'], errors='coerce')

In [ ]:
propinas_altas_fumadores = df[(df['smoker'] == 'Yes') & (df['tip'] > 5)]

print("--- Fumadores con propinas > 5 ---")
display(propinas_altas_fumadores)

--- Fumadores con propinas > 5 ---

     total_bill    tip   sex smoker  day    time  size   Columnas = Variables
0         50.81  10.00  Male    Yes  Sat  Dinner     3  Filas = Observaciones
49        25.89   5.16  Male    Yes  Sat  Dinner     4                      0
66        23.33   5.65  Male    Yes  Sun  Dinner     2                      0
241        7.25   5.15  Male    Yes  Sun  Dinner     2                      0

In [ ]:
baja= df.pop('Columnas = Variables')
df

     total_bill    tip     sex smoker   day    time  size
0         50.81  10.00    Male    Yes   Sat  Dinner     3
1         48.33   9.00    Male     No   Sat  Dinner     4
2         48.27   6.73    Male     No   Sat  Dinner     4
3         48.17   5.00    Male     No   Sun  Dinner     6
4         45.35   2.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
239        7.51   2.00    Male     No  Thur   Lunch     2
240        7.25   1.00  Female     No   Sat  Dinner     1
241        7.25   5.15    Male    Yes   Sun  Dinner     2
242        5.75   1.00  Female    Yes   Fri  Dinner     2
243        3.07   1.00  Female    Yes   Sat  Dinner     1

[244 rows x 7 columns]

In [ ]:
df = df.dropna(subset=['tip'])
display(df)
# elimine los Nan de la columna 'tip'

     total_bill    tip     sex smoker   day    time  size
0         50.81  10.00    Male    Yes   Sat  Dinner     3
1         48.33   9.00    Male     No   Sat  Dinner     4
2         48.27   6.73    Male     No   Sat  Dinner     4
3         48.17   5.00    Male     No   Sun  Dinner     6
4         45.35   2.50    Male    Yes   Sun  Dinner     3
..          ...    ...     ...    ...   ...     ...   ...
239        7.51   2.00    Male     No  Thur   Lunch     2
240        7.25   1.00  Female     No   Sat  Dinner     1
241        7.25   5.15    Male    Yes   Sun  Dinner     2
242        5.75   1.00  Female    Yes   Fri  Dinner     2
243        3.07   1.00  Female    Yes   Sat  Dinner     1

[181 rows x 7 columns]

In [3]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive